version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.flywaydb.flyway
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: org.apache.logging.log4j:log4j-to-slf4j
    versions:
    - 2.14.0
  - dependency-name: org.codehaus.groovy:groovy-xml
    versions:
    - 3.0.7
  - dependency-name: com.nimbusds:nimbus-jose-jwt
    versions:
    - 9.4.2
    - "9.5"
    - "9.6"
    - "9.7"
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.0
    - 10.0.2
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: org.mockito:mockito-inline
    versions:
    - 3.7.7
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.36.0
