version: '2.1'

services:
  rd-location-ref-api-db:
    build:
      context: database
    image: hmcts/rd-location-ref-api-db
    container_name: rd-location-ref-api-db
    volumes:
      - rd-location-ref-api-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-dbrdlocation}"
    ports:
      - 5457:5432
volumes:
  rd-location-ref-api-volume:
