server:
  port: 8099

management:
  endpoints:
    jmx:
      exposure:
        include: 'health'
    web:
      base-path: "/"
  endpoint:
    health:
      show-details: "always"

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: locrefdata
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
  cache:
    cache-names: token
    caffeine:
      spec: maximumSize=50,expireAfterWrite=1m

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: RD Location Ref API
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        registration:
          oidc:
            client-id: microservicekey-rd-location-ref-api
            client-secret: ${LOCATION_REF_API_S2S_SECRET:}
  jackson:
    date-format: yyyy-MM-dd
  flyway:
    enabled: true
    locations: ${LOCATIONS_DB:classpath:db/migration,classpath:db/postgres}
    schemas:
      - locrefdata
  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5458}/${POSTGRES_DB_NAME:dbrdlocationref}?currentSchema=locrefdata
    username: ${POSTGRES_USERNAME:dbrdlocationref}
    password: ${POSTGRES_PASSWORD:dbrdlocationref}
    min-idle: 1
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 600000
      poolName: LRDHikariCP
      maxLifetime: 1800000
      connectionTimeout: 30000
  config:
    import: "optional:configtree:/mnt/secrets/rd/"

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/readiness"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
### dependency configuration
idam:
  s2s-auth:
    totp_secret: ${LOCATION_REF_API_S2S_SECRET:}
    microservice: rd_location_ref_api
    url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
  s2s-authorised:
    services: ${LRD_S2S_AUTHORISED_SERVICES:rd_location_ref_api,payment_app,rd_caseworker_ref_api,rd_judicial_api}
  api.url: ${idam_url:https://idam-api.aat.platform.hmcts.net}

oidc.issuer: ${OIDC_ISSUER_URL:https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts}

loggingComponentName: RD-Location-Ref-Api

launchdarkly:
  sdk:
    key: ${LD_SDK_KEY:}
    environment: ${LAUNCH_DARKLY_ENV:local}
    user: rd

