server:
  port: 8099

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: RD Location Ref API
  jackson:
    date-format: yyyy-MM-dd
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: locrefdata

  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5458}/${POSTGRES_DB_NAME:locrefdata}?currentSchema=locrefdata
    username: ${POSTGRES_USERNAME:locrefdata}
    password: ${POSTGRES_PASSWORD:locrefdata}
    min-idle: 1
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
    - "/**"
  authorisedServices:
    - rd-location-ref-api

### dependency configuration
auth.provider.service.client.baseUrl: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
idam:
  s2s-auth:
    totp_secret: ${S2S_SECRET:}
    microservice: rd-location-ref-api
    url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

auth.idam.client.baseUrl: ${idam_url:https://idam-api.aat.platform.hmcts.net}

auth.idam.client.detailsUri: "/details"

feign:
  allow:
    headers:
      - authorization
      - serviceauthorization
