server:
  port: 8099

management:
  endpoints:
    jmx:
      exposure:
        include: 'health'
    web:
      base-path: "/"
  endpoint:
    health:
      show-details: "always"

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        default_schema: locrefdata
        jdbc:
          lob:
            non_contextual_creation: true

  main:
    allow-bean-definition-overriding: true
  application:
    name: RD Location Ref API
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        registration:
          oidc:
            client-id: microservicekey-rd-location-ref-api
            client-secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
  jackson:
    date-format: yyyy-MM-dd
  flyway:
    enabled: true
    locations: ${LOCATIONS_DB:classpath:db/migration,classpath:db/postgres}
    schemas:
      - locrefdata
  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5458}/${POSTGRES_DB_NAME:dbrdlocationref}?currentSchema=locrefdata
    username: ${POSTGRES_USERNAME:dbrdlocationref}
    password: ${POSTGRES_PASSWORD:dbrdlocationref}
    min-idle: 1
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
### dependency configuration
idam:
  s2s-auth:
    totp_secret: ${S2S_SECRET:}
    microservice: rd_location_ref_api
    url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
  s2s-authorised:
    services: ${LRD_S2S_AUTHORISED_SERVICES:rd_location_ref_api}
  api.url: ${idam_url:https://idam-api.aat.platform.hmcts.net}

oidc.issuer: ${OIDC_ISSUER_URL:https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts}

loggingComponentName: RD-Location-Ref-Api
