CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_epimms_id ON dbrdcaseworker.building_location(epimms_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_name ON dbrdcaseworker.building_location(UPPER(building_location_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_status ON dbrdcaseworker.building_location(UPPER(building_location_status));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_cluster_id ON dbrdcaseworker.building_location(cluster_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_region_id ON dbrdcaseworker.building_location(region_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_court_venue_epimms_id ON dbrdcaseworker.court_venue(epimms_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_court_name ON dbrdcaseworker.court_venue(UPPER(court_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_site_name ON dbrdcaseworker.court_venue(UPPER(site_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_postcode ON dbrdcaseworker.court_venue(UPPER(postcode));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_court_address ON dbrdcaseworker.court_venue(UPPER(court_address));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_court_type_status ON dbrdcaseworker.court_venue (court_type_id, court_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_epimms_court_type_status ON dbrdcaseworker.court_venue (epimms_id, court_type_id, court_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_region_status ON dbrdcaseworker.court_venue (region_id, court_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_building_name ON dbrdcaseworker.building_location (UPPER(building_location_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_status_open ON dbrdcaseworker.building_location (building_location_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cluster_id ON dbrdcaseworker.building_location (cluster_id);