java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_PORT: "{{ .Values.postgresql.postgresqlPort}}"
    LOCATIONS: "classpath:db/migration,classpath:db/postgres,classpath:db/migrationAks"
  postgresql:
    enabled: true
    postgresqlUsername: locrefdata
    postgresqlPassword: locrefdata
    postgresqlDatabase: locrefdata
    postgresqlPort: 5432
  keyVaults:
    rd:
      secrets:
        - AppInsightsInstrumentationKey
