java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    POSTGRES_PORT: "{{ .Values.postgresql.auth.port}}"
    LOCATIONS_DB: classpath:db/migration,classpath:db/postgres,classpath:db/migrationAks
    LAUNCH_DARKLY_ENV: "preview"
  postgresql:
    enabled: true
    auth:
      username: dbrdlocationref
      password: dbrdlocationref
      database: dbrdlocationref
      port: 5432
  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: location-ref-api-s2s-secret
          alias: LOCATION_REF_API_S2S_SECRET
